#!/bin/bash

if [ $# -lt 2 ] ; then
  echo "usage:   texloop tex-command main-file [A]"
  echo "   The main-file is file name without suffix."
  echo "   Type the letter A if you wish to run tex-command Allways,"
  echo "   no only if the main-file.tex is newer than main-file.log."
  exit 1
fi 

COMMAND=$1
MAINFILE=$2
MAINFILEBASE=`echo $2 | cut -d. -f1`
ALLWAYS=$3
SRCSPECIALS=$4

prefix=`echo $1 | cut -b 1-3`

if [ "$ALLWAYS" = "n" -o "$SRCSPECIALS" = "n" -o "$prefix" = "pdf" ] ; then
   echo ">>" $1 $2
   $1 $2
else
   echo ">>" $1 "-src-specials" $2
   $1 -src-specials $2
fi

if [ "$prefix" = "pdf" ] ; then
   PDF="true"
   VIEWFILE="$MAINFILEBASE.pdf"
else
   PDF="false"
   VIEWFILE="$MAINFILEBASE.dvi"
   read -p 'Paper (default A4): ' PAPER
   if [ "$PAPER" = "" ] ; then
      PAPER="A4"
       fi
fi

if [ -f $VIEWFILE ] ; then
   VIEWER="OK"
   if $PDF ; then
      xpdf -remote texloop.$$ $MAINFILEBASE.pdf &  
   else
      #xdvi $MAINFILEBASE &
      # https://vim.fandom.com/wiki/Vim_can_interact_with_xdvi
      xdvi -paper $PAPER -editor "uxterm -geometry 80x48 -bg #002200 -fg #cccccc -e vim --servername xdvi --remote" $MAINFILEBASE &
   fi
   VIEWPID=$!
else
   sleep 30d &
   VIEWPID=$!
   echo "texloop: The $VIEWFILE may be created later..."
fi

texrun() {
   trap "" USR1
   if [ $MAINFILEBASE.tex -nt $MAINFILEBASE.log -o $MAINFILE -nt $MAINFILEBASE.log -o "$ALLWAYS" = "A" ] ; then
if [ "$ALLWAYS" = "n" -o "$SRCSPECIALS" = "n" -o "$prefix" = "pdf" ] ; then
      echo ">>" $COMMAND $MAINFILE
      echo x | $COMMAND $MAINFILE
else
      echo ">>" $COMMAND "-src-specials" $MAINFILE
      echo x | $COMMAND "-src-specials" $MAINFILE
fi
      if [ $? -eq 0 ] ; then
	 if [ "$VIEWER" = "OK" ] ; then
            if $PDF ; then
               xpdf -remote texloop.$$ -reload
            else
	# https://bugs.launchpad.net/ubuntu/+source/texlive-bin/+bug/399148 
	       # kill -USR1 $VIEWPID
	       kill -USR1 $(ps a | grep xdvi.bin | awk 'NR==1{print $1}')
            fi
         else
            if [ -f $VIEWFILE ] ; then
               VIEWER="OK"
               kill $VIEWPID
               if $PDF ; then
                  xpdf -remote texloop.$$ $MAINFILEBASE.pdf &
               else
            	  xdvi $MAINFILEBASE &
               fi
               VIEWPID=$!
            fi
         fi
      fi
   fi
   trap texrun USR1
}
  
echo $$ > ~/.tlpid
echo $MAINFILEBASE > ~/.tlfname
trap texrun USR1
trap "kill $VIEWPID" INT

while ps -p $VIEWPID > /dev/null 
do
   wait
done
